//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SodingDemoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_UserInfo
    {
        
        [Display(Name = "USER ID:")]
        [Required(ErrorMessage = "ID is required")]
        public int Id { get; set; }
        [Display(Name = "NAME:")]
        [Required(ErrorMessage = "NAME is required")]
        public string Name { get; set; }
        [Display(Name = "DESCRIPTION:")]
        public string Description { get; set; }
        [Display(Name = "EMAIL:")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
